### ISSUE TITLE
WithUser is not prefixed with Oauth2

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/go-log-cache#15]
Everywhere else (besides LogCache itself), we prefix the `With` functions. However the `WithUser` is not prefixed, making it look like it belongs with `LogCache`.

https://github.com/cloudfoundry/go-log-cache/blob/1f76be6c14a0ab3abeb74f468ab74a5fccd76a63/oauth2_http_client.go#L61

Example:
https://github.com/cloudfoundry/go-log-cache/blob/1f76be6c14a0ab3abeb74f468ab74a5fccd76a63/oauth2_http_client.go#L54

**Comment by MasslessParticle** [comment]
Fixed by https://github.com/cloudfoundry/go-log-cache/commit/a5da457e9a2a3fe040aa15d61a609a06ba2b2fc7
