### ISSUE TITLE
Replace use of grpc.Dial and grpc.DialContext with grpc.NewClient

### ISSUE THREAD

**Issue by acrmp** [cloudfoundry/go-log-cache#173]
Recently the gRPC Go maintainers [shared their intention to deprecate grpc.Dial and grpc.DialContext](https://github.com/grpc/grpc-go/releases/tag/v1.63.1) and encourage users to use `grpc.NewClient` instead.

The go-log-cache API accepts dial options, [some of which will not be honoured after switching to grpc.NewClient](https://github.com/grpc/grpc-go/blob/b37cd8133af74174d5b9ead2617d6f74a063f9b8/clientconn.go#L124-L126). As a result when we switch we should major version bump our module.

The gRPC Gateway project has [recently switched to generating code that uses grpc.NewClient](https://github.com/grpc-ecosystem/grpc-gateway/pull/4174), although at time of writing these changes have not been released. We think we see that the generated code declares functions that take a context but don't use it.

Current plan is:

- Wait for gRPC Gateway project to cut a release that generates code using `grpc.NewClient`
- Bump our gRPC gateway dependency and re-generate. Check to see if the generated code accepts contexts that are unused.
- Bump our module version and cut a new release with release notes that indicate that specific dial options will no longer be honoured.

**Comment by ctlong** [comment]
Released in v3.0.0
