### ISSUE TITLE
Is this still the right repo for the log-cache client?

### ISSUE THREAD

**Issue by bradylove** [cloudfoundry/go-log-cache#23]
There is a client that lives at https://github.com/cloudfoundry/log-cache/tree/master/pkg/client. Which client is the correct one to use. This one does not have any documentation about being deprecated.

**Comment by toddboom** [comment]
We added a deprecation notice last month (9332900c05aebe14ebe11fa60a9acdd8c685add8), but it seems that the bottom of README wasn't the best place for this info. I moved it to the top of the README and added some style for emphasis.

In short, the client that lives in the log-cache repo is the right one to use going forward.
