### ISSUE TITLE
Walk should not rely on client clock being synchronized with server clock

### ISSUE THREAD

**Issue by nickjameswebb** [cloudfoundry/go-log-cache#28]
## Context

Client is using `time.Now()` [here](https://github.com/cloudfoundry/go-log-cache/blob/master/walk.go#L75) to filter out log envelopes when walking. This can cause unexpected/confusing behavior because there are no guarantees that the client and servers will be synchronized with regards to clock.

There are three client clock cases:
  - Client clock is synchronized with server clock. Everything is fine.
  - Client clock is behind the server clock. `Walk` will filter out all logs until the client clock catches up to the log envelopes.
  - Client clock is ahead of the server clock. Log loss will occur in a multi-Doppler setting because the `WalkDelay` will be overwhelmed by the difference in clock between the client and server. 

- See [dora_logs.tar.gz](https://github.com/cloudfoundry/go-log-cache/files/4405703/dora_logs.tar.gz) for examples of log output when doing a `cf push` for each of the three cases

## Possible Solution

From @ ericpromislow

Currently `logcache.Walk` calculates the time with this equation:

`withDelay := time.Now().Add(-c.delay).UnixNano()`
That `time.Now()` is client time, we want it to be logcacheNode's time. Assuming all dopplers' clocks are synchronized, we actually want it to be:

`desiredWithDelay := dopplerTimeNow.Add(-c.delay).UnixNano() => logcacheTime - specifiedDelay`
We can calc the client delta by sending an info request to logcache and getting the time from the header:

`clientDelta := time.Now() - logcacheTime`
If we call `logcache.Walk` with the arg

`logcache.WithWalkDelay(desiredDelay=2*time.Second + clientDelta)`,
we're setting

```
withDelay := time.Now().Add(-c.delay).UnixNano() =>
   time.Now - specifiedDelay =>
   time.Now() - (desiredDelay + time.Now() - logCacheTime) =>
   logCacheTime - desiredDelay
```
and now `logcache.Walk` will be respecting a delay on its clock, not the client's. This works whether the client clock is
ahead of the dopper's or behind it.

This all assumes that the clocks on the doppler nodes and runtime containers are well synchronized. If they aren't, it would be
better to specify a longer delay and then wait by a similar amount before calling `stopStreaming()` in the channel consumers.

**Comment by pianohacker** [comment]
It seems like there's something hinting at this in the Log Cache API: https://github.com/cloudfoundry/log-cache-release/tree/develop/src#get-apiv1readsource-id We'll need to discuss that on our side.
