### ISSUE TITLE
Default walk delay should be set to 2 seconds

### ISSUE THREAD

**Issue by JenGoldstrich** [cloudfoundry/go-log-cache#29]
The cf CLI team has observed that when we use the default Log Cache walk delay of 1 second on a multi doppler foundation we see fairly consistent dropped logs even when the clock and server clock are synchronized.  We suggest bumping this to 2 seconds which seems to alleviate a lot of these failures.

[More information here](https://www.pivotaltracker.com/story/show/171759407/comments/212399984)

Thanks!
Jenna and @nickjameswebb

**Comment by pianohacker** [comment]
Done in https://github.com/cloudfoundry/go-log-cache/commit/3f87d731aaa97e24861c3a35f6d57c6dbbd4cdb8 .
