### ISSUE TITLE
Getting latest version of the this repo results in v1 tag

### ISSUE THREAD

**Issue by winkingturtle-vmw** [cloudfoundry/go-log-cache#80]
When using go tooling to import this repo, it looks to be that `go get -u code.cloudfoundry.org/go-log-cache` results in getting [v1.0.0 tag](https://github.com/cloudfoundry/go-log-cache/releases/tag/v1.0.0). It'd be ideal if that tag was removed or if we could find an easier way to import the latest version of this repository. Here are the commands I tried and failed to update the latest commit:

```
go get -u code.cloudfoundry.org/go-log-cache
go get -u code.cloudfoundry.org/go-log-cache@latest
```

I was successful with only the following command:

```
go get -u code.cloudfoundry.org/go-log-cache@main
```
My understanding is that we want users to fetch the latest changes on main branch, but unless someone explicitly attempt to pull from the main, it will always pull a fairly outdated version of this repository and will not update.

**Comment by ctlong** [comment]
Hi @winkingturtle-vmw! We're aware of the problem, thanks for describing it so well though :).

It's on our to-do list to create a pipeline tracking this repo and start cutting new releases.

**Comment by ctlong** [comment]
With the `v2.0.0` tag cut last week, we intend to start cutting more regular semver releases for this tool.

Please upgrade your imports to append the `/v2` path to the go-log-cache module import.
